server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${PROJECT_NAME}  
      
  profiles:
    active: "dev"
    
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    open-in-view: false
    show-sql: true

  hikari:
    maximum-pool-size: 10

  flyway:
    locations: "classpath:db/migration"
    enabled: true
        
springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    enabled: true